resources:
 pipelines:
   - pipeline: P1
     source: publishPipelineArtifact
     project: pr
     
stages:
 - stage: ConsumeArtifact
   jobs:
     - deployment: deployJob
       environment: envionment2
       pool: Default
       strategy:
        runOnce:
          deploy:
            steps:
              - powershell: |
                 ls $(Build.ArtifactStagingDirectory)/
     - job: job1
       pool: 
        name: Default
       steps:
        - powershell: |
                 ls $(Build.ArtifactStagingDirectory)/
        - download: P1
          artifact: artifact1
