resources:
  packages:
   - package: somePackage
     type: Nuget
     connection: gh
     name: NewtonSoft.json
     version: 11.0.3
     
stages:
 - stage: ConsumeArtifact
   jobs:
     - job: job1
       pool: 
        name: Default
       steps:
        - powershell: |
                 ls $(Build.ArtifactStagingDirectory)/
        - download: P1
          artifact: artifact1
        - download: P2
          artifact: artifact2
