resources:
  packages:
   - package: somePackage
     type: Nuget
     connection: gh-rg
     name: romil07/OctocatApp
     version: 2.1.1
     
stages:
 - stage: ConsumeArtifact
   jobs:
     - job: job1
       pool: 
        name: Default
       steps:
        - getPackage: somePackage
