resources:
 pipelines:
   - pipeline: P1
     source: romil07.yaml
     project: pr
 packages:
   - package: somePackage
     type: Nuget
     connection: gh
     package: NewtonSoft.json
     version: 11.0.3
     
stages:
 - stage: ConsumeArtifact
   jobs:
     - deployment: deployJob
       environment: envionment2
       pool: Default
       strategy:
        runOnce:
          deploy:
            steps:
              - powershell: |
                 ls $(Build.ArtifactStagingDirectory)/
     - job: job1
       pool: 
        name: Default
       steps:
        - powershell: |
                 ls $(Build.ArtifactStagingDirectory)/
        - download: P1
          artifact: artifact1
