resources:
  packages:
   - package: somePackage
     type: Nuget
     connection: gh-rg
     name: NewtonSoft.json
     version: 11.0.3
     
stages:
 - stage: ConsumeArtifact
   jobs:
     - job: job1
       pool: 
        name: Default
       steps:
        - getPackage: somePackage
